openapi: 3.0.1
info:
  title: Product API
  description: Pactflow Product API demo
  version: 1.0.0
paths:
  /products/products:
    post:
      summary: Create a product
      description: Creates a new product
      operationId: createProduct
      requestBody:
        description: Create a new Product
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            examples:
              application/json:
                value:
                  id: "1234"
                  type: "food"
                  price: 42
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                  $ref: '#/components/schemas/Product'
              examples:
                application/json:
                  value:
                    id: "1234"
                    type: "food"
                    price: 42
    get:
      summary: List all products
      description: Returns all products
      operationId: getAllProducts
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                application/json:
                  value:
                    - id: "1234"
                      type: "food"
                      price: 42
                      # name: "pizza"
                      # version: "1.0.0"
                      # see https://github.com/apiaryio/dredd/issues/1430 for why
        "400":
          description: Invalid ID supplied
          content: {}
  /products/product/{id}:
    get:
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductByID
      parameters:
      - name: id
        in: path
        description: ID of product to get
        schema:
          type: string
        required: true
        example: 10
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                application/json:
                  value:
                    id: "1234"
                    type: "food"
                    price: 42
                    # name: "pizza"
                    # version: "1.0.0"
                    # see https://github.com/apiaryio/dredd/issues/1430 for why
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Product not found
          content: {}
  /lotDetails/display_lot_summary:
    get:
      summary: Get lot summary by ID
      description: Returns a single lot summary
      operationId: display_lot_summary
      parameters:
      - name: mft_key
        in: query
        description: key of object type to summarize
        schema:
          type: string
        required: true
        example: "Protein Lot Num"
      - name: value
        in: query
        description: key of object type to summarize
        schema:
          type: string
        required: true
        example: "MFT-000123-001"
      responses:
        "200":
          description: successful operation
          content:
            "application/json; charset=utf-8":
              schema:
                $ref: '#/components/schemas/Lot_Summary'
              examples:
                application/json:
                  value:
                    lot_summary:
                      parent:
                        parent_name:
                          key: Protein Name
                          value: insulin
                          type: string
                          template_loc:
                            down: 1
                            right: 0
                            value: right
                        parent_corp_name:
                          key: Protein Num
                          value: MFT-000123
                          type: string
                          template_loc:
                            down: 2
                            right: 0
                            value: right
                      lot:
                        corp_name:
                          key: Protein Lot Num
                          value: MFT-000123-001
                          type: string
                          template_loc:
                            down: 3
                            right: 0
                            value: right
                        lot_produced_date:
                          key: Production Date
                          value: '2022 Mar 03 05:12 PDT'
                          type: date
                          template_loc:
                            down: 4
                            right: 0
                            value: right
                        lot_produced_by:
                          key: Produced By
                          value: john.mcneil
                          type: string
                          template_loc:
                            down: 5
                            right: 1
                            value: right
                        lot_purified_date:
                          key: Purification Date
                          value: '2022 Mar 07 09:00 PDT'
                          type: date
                          template_loc:
                            down: 6
                            right: 0
                            value: right
                        lot_purity:
                          key: Purity (%)
                          value: '92'
                          type: percent
                          template_loc:
                            down: 7
                            right: 1
                            value: right
                        lot_amount_produced:
                          key: Amount Produced (mg)
                          value: '22'
                          type: number
                          template_loc:
                            down: 8
                            right: 1
                            value: right
                        lot_eln_record:
                          key: ELN Record
                          value: '[Lot MFT-000123-001 Production Production](http://eln.com/eln12355)'
                          type: url
                          template_loc:
                            down: 9
                            right: 0
                            value: right
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Product not found
          content: {}
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
        type:
          type: string
        name:
          type: string
        version:
          type: string
        price:
          type: number
    Lot_Summary:
      type: object
      properties:
        lot_summary:
          type: object
          properties:
            lot:
              type: object
            parent:
              type: object


